import type { languages } from 'monaco-editor/editor/editor.api.js';

/** Read-only Svelte highlighting; embedded scripts/styles use Monaco's grammars. */
export const svelteLanguage: languages.IMonarchLanguage = {
  tokenPostfix: '.svelte',
  keywords: [
    'if',
    'else',
    'each',
    'as',
    'await',
    'then',
    'catch',
    'key',
    'snippet',
    'render',
    'html',
    'debug',
    'const',
    'let',
    'var',
    'return',
    'true',
    'false',
    'null',
    'undefined',
    'new',
    'typeof',
    'instanceof',
    'in',
    'of',
    'function',
    'async',
    'throw',
  ],
  tokenizer: {
    root: [
      [/<!--/, 'comment', '@comment'],
      [
        /(<)(script)\b/,
        ['delimiter', { token: 'tag', next: '@scriptTag.javascript' }],
      ],
      [/(<)(style)\b/, ['delimiter', { token: 'tag', next: '@styleTag' }]],
      [/(<\/?)([\w:.-]+)/, ['delimiter', { token: 'tag', next: '@tag' }]],
      { include: '@template' },
      [/[^<{]+/, ''],
      [/./, ''],
    ],
    template: [
      [
        /(\{)([#:/@])([a-z]+)\b/,
        [
          'delimiter.bracket',
          'keyword',
          { token: 'keyword', next: '@expression' },
        ],
      ],
      [/\{/, 'delimiter.bracket', '@expression'],
    ],
    tag: [
      [/\/?>/, 'delimiter', '@pop'],
      { include: '@template' },
      [/"/, 'attribute.value', '@doubleAttribute'],
      [/'/, 'attribute.value', '@singleAttribute'],
      [/[\w$:.-]+/, 'attribute.name'],
      [/=/, 'delimiter'],
      [/\s+/, ''],
      [/./, ''],
    ],
    doubleAttribute: [
      [/"/, 'attribute.value', '@pop'],
      { include: '@template' },
      [/[^"{]+/, 'attribute.value'],
    ],
    singleAttribute: [
      [/'/, 'attribute.value', '@pop'],
      { include: '@template' },
      [/[^'{]+/, 'attribute.value'],
    ],
    expression: [
      [/\{/, 'delimiter.bracket', '@expression'],
      [/\}/, 'delimiter.bracket', '@pop'],
      [/\/\*/, 'comment', '@expressionComment'],
      [/\/\/.*$/, 'comment'],
      [/"/, 'string', '@doubleString'],
      [/'/, 'string', '@singleString'],
      [/`/, 'string', '@templateString'],
      [/\$[\w$]+/, 'predefined'],
      [
        /[A-Za-z_$][\w$]*/,
        { cases: { '@keywords': 'keyword', '@default': 'identifier' } },
      ],
      [/\d+(?:\.\d+)?/, 'number'],
      [/[()[\]]/, 'delimiter.bracket'],
      [/[=+\-*/%!?&|<>:]+/, 'operator'],
      [/[.,;]/, 'delimiter'],
      [/\s+/, ''],
      [/./, ''],
    ],
    doubleString: [
      [/\\./, 'string.escape'],
      [/"/, 'string', '@pop'],
      [/[^"\\]+/, 'string'],
    ],
    singleString: [
      [/\\./, 'string.escape'],
      [/'/, 'string', '@pop'],
      [/[^'\\]+/, 'string'],
    ],
    templateString: [
      [/\\./, 'string.escape'],
      [/`/, 'string', '@pop'],
      [/[^`\\]+/, 'string'],
    ],
    expressionComment: [
      [/\*\//, 'comment', '@pop'],
      [/[^*]+/, 'comment'],
      [/./, 'comment'],
    ],
    comment: [
      [/-->/, 'comment', '@pop'],
      [/[^-]+/, 'comment'],
      [/./, 'comment'],
    ],
    scriptTag: [
      [
        /(lang)(\s*=\s*)(["'](?:ts|typescript)["'])/,
        [
          'attribute.name',
          'delimiter',
          { token: 'attribute.value', switchTo: '@scriptTag.typescript' },
        ],
      ],
      [/>/, { token: 'delimiter', next: '@scriptBody', nextEmbedded: '$S2' }],
      [/"[^"]*"|'[^']*'/, 'attribute.value'],
      [/[\w:.-]+/, 'attribute.name'],
      [/=/, 'delimiter'],
      [/\s+/, ''],
      [/./, ''],
    ],
    scriptBody: [
      [
        /<\/script\s*>/,
        { token: 'tag', next: '@popall', nextEmbedded: '@pop' },
      ],
    ],
    styleTag: [
      [/>/, { token: 'delimiter', next: '@styleBody', nextEmbedded: 'css' }],
      [/"[^"]*"|'[^']*'/, 'attribute.value'],
      [/[\w:.-]+/, 'attribute.name'],
      [/=/, 'delimiter'],
      [/\s+/, ''],
      [/./, ''],
    ],
    styleBody: [
      [/<\/style\s*>/, { token: 'tag', next: '@popall', nextEmbedded: '@pop' }],
    ],
  },
};
